name: Dotnet Lint

run-name: Run Dotnet Lint(${{ github.event.number }})

on:
  pull_request:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
        type: string

jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      PR_NUMBER: ${{ github.event.inputs.number }}
      WORKSPACE: ${{ vars.WORKSPACE }}
    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        run: |
          echo running on branch $GITHUB_BASE_REF
          echo running on branch $GITHUB_HEAD_REF
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Dotnet Format
        run: |
          dotnet tool install -g dotnet-format
          dotnet-format ${WORKSPACE} --report dotnet-format-report.json
      - name: Check Report
        run: |
          cat ${WORKSPACE}/dotnet-format-report.json
          rm ${WORKSPACE}/dotnet-format-report.json
      - name: Git commit & push
        run: |
          git status
          git diff
          git add ${WORKSPACE}
          git config --local user.email "yejun614@naver.com"
          git config --local user.name "Dotnet Format Bot (by YeJun, Jung)"
          git commit -m "[Style] dotnet format(${PR_NUMBER})"
          git push origin $GITHUB_HEAD_REF