name: Dotnet Lint
run-name: \[${{ github.event.number }}\] Run Dotnet Lint
on:
  pull_request:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
        type: string
jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      PR_NUMBER: ${{ github.event.inputs.number }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: |
        dotnet tool install -g dotnet-format
        dotnet-format server.sln --report dotnet-format-report.json
      - run: |
        cat dotnet-format-report.json
        rm dotnet-format-report.json
      - run: |
        git add .
        git diff
        git config --local user.email "yejun614@naver.com"
        git config --local user.name "Dotnet Format Bot (by YeJun, Jung)"
        git commit -m "[Style] dotnet format(${PR_NUMBER})"
        git push