name: Dotnet EF Migrations

run-name: Run Dotnet EntityFramework Migrations

on:
  push:
    branches:
      - develop

jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      PR_NUMBER: ${{ github.event.inputs.number }}
      WORKSPACE: ${{ vars.WORKSPACE }}
    steps:
      - name: Branch name
        run: |
          echo test ${{ github.ref_name }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Dotnet EntityFramework Migration
        run: |
          cd ${WORKSPACE}
          dotnet tool install --global dotnet-ef
          dotnet ef migrations add "${{ github.event.head_commit.message }}"
          dotnet ef database update
      - name: Git commit & push
        run: |
          git config --local user.email "yejun614@naver.com"
          git config --local user.name "Dotnet Format Bot (by YeJun, Jung)"
          echo --------------------- STATUS ---------------------
          git status
          echo ---------------------  DIFF  ---------------------
          git diff
          echo ---------------------  ADD   ---------------------
          git add ${WORKSPACE}
          echo --------------------- COMMIT ---------------------
          git commit -m "[Chore] Auto EntityFramework Migrations"
          echo --------------------- BRANCH ---------------------
          git branch
          echo ---------------------  LOG   ---------------------
          git log
          echo ---------------------  PUSH  ---------------------
          git push origin ${{ github.ref_name }}