name: Dotnet Lint

run-name: Run Dotnet Lint(${{ github.event.number }})

on:
  pull_request:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
        type: string

jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      PR_NUMBER: ${{ github.event.inputs.number }}
      WORKSPACE: ${{ vars.WORKSPACE }}
    steps:
      - name: Branch name
        run: |
          echo running on branch $GITHUB_BASE_REF
          echo running on branch $GITHUB_HEAD_REF
          echo test ${{ github.ref_name }}
      - uses: actions/checkout@v3
        with:
          ref: $GITHUB_HEAD_REF
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Dotnet Format
        run: |
          dotnet tool install -g dotnet-format
          dotnet-format ${WORKSPACE} --report dotnet-format-report.json
      - name: Check Report
        run: |
          cat ${WORKSPACE}/dotnet-format-report.json
          rm ${WORKSPACE}/dotnet-format-report.json
      - name: Git commit & push
        run: |
          echo -------------------------------------------------
          git status
          echo -------------------------------------------------
          git diff
          echo -------------------------------------------------
          git add ${WORKSPACE}
          echo -------------------------------------------------
          git config --local user.email "yejun614@naver.com"
          echo -------------------------------------------------
          git config --local user.name "Dotnet Format Bot (by YeJun, Jung)"
          echo -------------------------------------------------
          git commit -m "[Style] Auto dotnet format (#${{ github.event.inputs.number }})"
          echo -------------------------------------------------
          git branch
          git log
          git push origin $GITHUB_HEAD_REF
          echo -------------------------------------------------